
services: 

  backend:
    build: 
      context: backend
    container_name: backend
    restart: always
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3838:3838"
    command: node app.js

  frontend:
    build: 
      context: frontend
    container_name: frontend
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    tty: true
    ports: 
      - "5173:5173"
    command: npm run preview

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - node-network
    depends_on:
       - backend
       - frontend
  
networks: 
  node-network:
    driver: bridge
